#!/usr/bin/env python3
"""Stage the imported Sponza: the scene `balaur import` wrote, plus the camera,
the light and the environment a still needs.

Kept apart from the import so re-importing the model never loses the staging,
and the staging never has to know the model's 25 materials."""

import pathlib
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
STAGE = """
[[nodes]]
id = "n_shot"
name = "Shot"
parent = "n_sponza"
script = { source = "scripts/shot.rn" }

[[nodes]]
id = "n_camera"
name = "Camera"
parent = "n_sponza"

[nodes.transform]
position = [-7.5, 2.0, 0.0]

[nodes.camera]
kind = "3d"
look_at = [8.0, 3.0, 0.0]
post = ["ssao", "bloom", "tonemap", "vignette", "fxaa"]
bloom_threshold = 1.6
bloom_intensity = 0.35
vignette_amount = 0.32
# Sponza is thirty units across, so the occlusion pass reads at its scale.
ssao_radius = 0.6
ssao_bias = 0.25

[[nodes]]
id = "n_env"
name = "Environment"
parent = "n_sponza"

[nodes.environment]
sky = "skies/clear-day.png"
sky_intensity = 2.2
show_sky = true
tonemap = "aces"
exposure = 1.1
ambient = "#000000"
shadows = true
shadow_resolution = 2048
shadow_distance = 40.0

[[nodes]]
id = "n_sun"
name = "Sun"
parent = "n_sponza"

[nodes.transform]
position = [6.0, 18.0, 4.0]
rotation_euler = [-1.15, 0.5, 0.0]

[nodes.light3d]
kind = "directional"
color = "#fff4e0"
intensity = 5.0
shadows = true

# The court is a room, so what the marble reflects is the room rather than the
# sky above the building.
[[nodes]]
id = "n_probe"
name = "Court"
parent = "n_sponza"

[nodes.transform]
position = [0.0, 5.0, 0.0]

[nodes.reflection_probe]
half_extents = [16.0, 8.0, 7.0]
falloff = 2.0
intensity = 1.0
"""


def main():
    imported = (ROOT / "scenes" / "sponza.toml").read_text()
    out = ROOT / "scenes" / "main.toml"
    out.write_text(
        "# Generated by scripts/stage.py: the imported scene plus its staging.\n"
        "# Edit the staging there, not here.\n\n" + imported + STAGE
    )
    scene = tomllib.loads(out.read_text())
    print(f"{out.name}: {len(scene['assets'])} materials, {len(scene['nodes'])} nodes")


if __name__ == "__main__":
    main()
