#!/usr/bin/env python3
"""Stage the imported Sponza: the scene `balaur import` wrote, plus the camera,
the light and the environment a still needs.

Kept apart from the import so re-importing the model never loses the staging,
and the staging never has to know the model's 25 materials."""

import pathlib
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
STAGE = """
# Every triangle in the file as one asset, for the collider to be fitted to.
[[assets]]
id = "sponza_shell"
type = "mesh"
source = "models/sponza.gltf"

# The arcade as static geometry. No `body3d`, so it never moves and never
# costs the solver anything; `fix_internal_edges` keeps the player from
# catching on the seams between its 260 thousand triangles.
[[nodes]]
id = "n_shell"
name = "Shell"
parent = "n_sponza"

[nodes.collider3d]
kind = "trimesh"
mesh = "#sponza_shell"
fix_internal_edges = true
clean = true

# Eyes on a capsule, from the editor's library: WASD walks, the mouse looks.
[[nodes]]
id = "n_player"
name = "Player"
parent = "n_sponza"
script = { source = "scripts/first_person.rn", props = { yaw = -90.0 } }

[nodes.transform]
position = [-9.0, 1.6, 0.0]

[nodes.character3d]
snap_to_ground = 0.3
autostep = 0.4

[nodes.collider3d]
kind = "capsule"
radius = 0.35
height = 1.2

# The eye, on its own node: the capsule's own height wobbles a millimetre or
# two per triangle it crosses, and the rig keeps that off the camera.
[[nodes]]
id = "n_eye"
name = "Eye"
parent = "n_player"

[nodes.transform]
position = [0.0, 0.7, 0.0]

[nodes.camera]
kind = "3d"
look_at = [8.0, 3.0, 0.0]
post = ["ssao", "bloom", "tonemap", "vignette", "fxaa"]

[[nodes]]
id = "n_env"
name = "Environment"
parent = "n_sponza"

[nodes.environment]
sky = "skies/clear-day.png"
show_sky = true
tonemap = "aces"
ambient = "#000000"
shadows = true
shadow_distance = 40.0

[[nodes]]
id = "n_sun"
name = "Sun"
parent = "n_sponza"

[nodes.transform]
position = [6.0, 18.0, 4.0]
rotation_euler = [-1.15, 0.5, 0.0]

[nodes.light3d]
kind = "directional"
color = "#fff4e0"
shadows = true

# The court is a room, so what the marble reflects is the room rather than the
# sky above the building.
[[nodes]]
id = "n_probe"
name = "Court"
parent = "n_sponza"

[nodes.transform]
position = [0.0, 5.0, 0.0]

[nodes.reflection_probe]
half_extents = [16.0, 8.0, 7.0]
falloff = 2.0
intensity = 1.0
[[nodes]]
id = "n_drive"
name = "Drive"
parent = "n_player"

[nodes.script]
source = "scripts/flythrough.rn"
[nodes.script.props]
# Set when the clip or the still is being taken; empty for a normal run.
shot = ""
frames = ""

"""


def main():
    imported = (ROOT / "scenes" / "sponza.toml").read_text()
    out = ROOT / "scenes" / "main.toml"
    out.write_text(
        "# Generated by scripts/stage.py: the imported scene plus its staging.\n"
        "# Edit the staging there, not here.\n\n" + imported + STAGE
    )
    scene = tomllib.loads(out.read_text())
    print(f"{out.name}: {len(scene['assets'])} materials, {len(scene['nodes'])} nodes")


if __name__ == "__main__":
    main()
